# Numpy (Numerical Python)

### 1. 넘파이 설치 확인

In [1]:
import numpy as np
print(np.__version__)

2.0.1


### 2. 넘파이 배열(ndarray) 생성과 속성 확인

In [2]:
a1 = np.array([1,2,3])
print(a1, a1.dtype, a1.ndim, a1.shape, a1.size)#(3,)로 표현하여 튜플임을 확인시킴
a2 = np.array((1,2,3))
print(a2,type(a2),a2.dtype, a2.ndim, a2.shape, a2.size)#(3,)로 표현하여 튜플임을 확인시킴
    

[1 2 3] int64 1 (3,) 3
[1 2 3] <class 'numpy.ndarray'> int64 1 (3,) 3


In [3]:
a3 = np.array([[1,2,3],[4,5,6]])
print(a3)
print(type(a3),a3.dtype, a3.ndim, a3.shape, a3.size)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'> int64 2 (2, 3) 6


In [4]:
a1 = np.array([1,2,3], dtype=float)
print(a1, a1.dtype, a1.ndim, a1.shape, a1.size)

[1. 2. 3.] float64 1 (3,) 3


In [5]:
a6 = np.array([1,4,5,'8'])
print(a6)
print(type(a6), a6.dtype, a6.ndim, a6.shape, a6.size)
# < 타입은 데이터 저장시 순서대로 저장안됨
# 막 뒤즙음 

['1' '4' '5' '8']
<class 'numpy.ndarray'> <U21 1 (4,) 4


In [6]:
a6 = np.array([1,4,5,'8'], int)
print(a6)
print(type(a6), a6.dtype, a6.ndim, a6.shape, a6.size)

[1 4 5 8]
<class 'numpy.ndarray'> int64 1 (4,) 4


In [7]:
test_list = [[1,4,5,8], [1,4,5]]
np.array(test_list)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### 3. Indexing

In [ ]:
d3 = np.arange(12).reshape(2,2,3) # 0~11
print(d3)


In [ ]:
d3[0] = 50
print(d3)

In [ ]:
# broadcasting : 값을 전파하여 적용시킴?
d3[1,0] = 30
print(d3)

### 4. slicing

In [ ]:
d2 = np.arange(1,11).reshape(2,-1) # 알아서 계산하여 반환
print(d2)
d2[:,:] = -1
print(d2)

### 5.Boolean Indexing

In [ ]:
data = np.array([4,6,7,3,2,0])
print(data > 3)
print(data[data>3])

### 6. 넘파이 배열의 정렬

In [ ]:
# [연습문제] 성적순으로 출력
names = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
scores = np.array([78, 95, 84, 98, 88])

score_sorted_index = np.argsort(scores)[::-1]
print(score_sorted_index)
print(names[score_sorted_index])

# 교안 내 실습 파일 실행

#### 기존 데이터로부터 넘파이 배열 생성

In [ ]:
a1 = np.array([1,2,3])
a2 = np.array((1,2,3))
a3 = np.array([[1,2,3], [4,5,6]])
a4 = np.array([1,2,3], dtype=float)
a5 = np.array([1,2,3], float)
a6 = np.array([1,4,5,"8"])
a7 = np.array([1,4,5,"8"], int)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)
print(a7)

#### 인덱싱

In [9]:
d = np.array([1,2,3,4,5,6,7,8,9])
print(d[0], d[1], d[2], d[-1], d[-2])

1 2 3 9 8


In [10]:
d2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(d2[0][0]) # 배열명 [행][열] 형태
print(d2[0, 0]) 
print(d2[1,1])
print(d2[1,-1])

1
1
7
10


In [11]:
d3 = np.arange(12).reshape(2,2,3)
print(d3[0][0][0]) # 배열명[면][행][열] 형태
print(d3[0, 0, 0]) # 배열명[면, 행, 열] 형태
print(d3[1,1,2])
print(d3[-1,-1,-1])

d[3] = 100
d2[1,1] = 100
d3[1,1,1] = 1000

d2[0] = 50
d3[0] = 50
d3[1,0] = 30

0
0
11
11


#### 슬라이싱

In [12]:
d = np.array([1,2,3,4,5,6,7,8,9])
print(d)
print(d[2:3], d[:], d[:-1])
print(d[::2], d[::-1])

[1 2 3 4 5 6 7 8 9]
[3] [1 2 3 4 5 6 7 8 9] [1 2 3 4 5 6 7 8]
[1 3 5 7 9] [9 8 7 6 5 4 3 2 1]


In [13]:
d2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(d2[0])
print(d2[0, :])
print(d2[:,:-1])
print(d2[::2,::2])


[1 2 3 4 5]
[1 2 3 4 5]
[[1 2 3 4]
 [6 7 8 9]]
[[1 3 5]]


In [15]:
d3 = np.arange(12).reshape(2,2,3)
print(d3)
print(d3[:,:-1,:-1])
print(d3[:,1:,1:])
print(d3[:,:,-1])
print(d3[:,-1,-1])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[0 1]]

 [[6 7]]]
[[[ 4  5]]

 [[10 11]]]
[[ 2  5]
 [ 8 11]]
[ 5 11]


In [17]:
d2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(d2)
print(d2[::2,::3])
d2[::2,::3] = 30
print(d2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 4]]
[[30  2  3 30  5]
 [ 6  7  8  9 10]]


In [18]:
d2[:,:] = -1
print(d2)

[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


#### 팬시 인덱싱(Fancy indexing)

In [22]:
f = np.array([4,6,7,3,2,0])
indexes = np.array([1,2,0,2,2,2])
f[indexes]
print(f[indexes])
f2 = np.array([[1,4], [9,16]])
x = np.array([0,1,1,1,0,0])
y = np.array([0,0,0,1,1,1])
f2[x,y]

[6 7 4 7 7 7]


array([ 1,  9,  9, 16,  4,  4])

#### 넘파이 배열의 정렬

In [25]:
numbers = np.array([2,8,9,7,3,1,4,5,6])
sorted_numbers = np.sort(numbers)
print(numbers)
print(sorted_numbers)
print(sorted_numbers[::-1])

numbers.sort()
print(numbers)

[2 8 9 7 3 1 4 5 6]
[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[1 2 3 4 5 6 7 8 9]


In [26]:
arr2d =np.array([[5,6,7,8],
                 [4,3,2,1],
                 [10,9,12,11]])
print(arr2d)

print(np.sort(arr2d))
print(np.sort(arr2d, axis=1))
print(np.sort(arr2d, axis=0))

[[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]
[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
[[ 4  3  2  1]
 [ 5  6  7  8]
 [10  9 12 11]]


In [27]:
# argsort 함수
numbers = np.array([2,8,9,7,3,1,4,5,6])
sorted_indexes = np.argsort(numbers)
print(sorted_indexes)

[5 0 4 6 7 8 3 1 2]


#### 넘파이 배열의 사칙연산

In [29]:
# 브로드캐스팅
x = np.arange(1, 7).reshape(2,3)
x + x
x + 2
y = np.array([10, 20, 30])
print(x+y)


[[11 22 33]
 [14 25 36]]


In [33]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])

# 1. sum, mean, max, min
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))

print(a.mean())
print(a.mean(axis=0))
print(a.mean(axis=1))

print(a.max())
print(a.max(axis=0))
print(a.max(axis=1))

print(a.min())
print(a.min(axis=0))
print(a.min(axis=1))

# 2. argmax, argmin
print(a.argmax())
print(a.argmax(axis=0))
print(a.argmax(axis=1))

print(a.argmin())
print(a.argmin(axis=0))
print(a.argmin(axis=1))

# 3. all
print(a.all())
print(np.all(a > 3))

# 4. any
print(a.any())
print(np.any(a > 4))

21
[5 7 9]
[ 6 15]
3.5
[2.5 3.5 4.5]
[2. 5.]
6
[4 5 6]
[3 6]
1
[1 2 3]
[1 4]
5
[1 1 1]
[2 2]
0
[0 0 0]
[0 0]
True
False
True
True


In [34]:
# 1. 배열에 결측치가 하나라도 포함되어 있는지 확인
data = np.array([1, 2, np.nan, 4])
print(np.any(np.isnan(data)))

# 2. 두 배열이 완전히 동일한지 확인
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
print(np.all(arr1 == arr2)) # 요쇼별 비교 후 전체 확인

True
True
